name: Math4ht
on: push

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - run: mkdir html

      - name: Run make4ht
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: 2024
          run: |
            make4ht -d html -u main.tex "mathml" -c config.cfg

      - uses: actions/upload-artifact@v4
        with:
          name: html
          path: html/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: html
