name: Pandoc
on: push

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - run: mkdir output

      - uses: docker://pandoc/latex:latest
        with:
          args: --mathml --output=output/index.html README.md

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: output
