name: Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: mkdir output

      - uses: docker://pandoc/latex:latest
        with:
          args: --mathml --output=output/index.html README.md

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
